project_id = "nqfcdcfzxehpjhlmqudq"

[functions.scrape-leads]
verify_jwt = true

[functions.ai-draft-email]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.ai-analyze-contact]
verify_jwt = true

[functions.ai-workflow-executor]
verify_jwt = false

[functions.track-email-event]
verify_jwt = false

[functions.scheduled-search-executor]
verify_jwt = false